apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Namespace }}
  template:
    metadata:
      labels:
        app: {{ .Release.Namespace }}
    spec:
      containers:
        - name: app
          image: {{ .Values.image | required "image is required "}}
          ports:
            - containerPort: {{ .Values.containerPort }}
          env:
              # We've already created the secrets with kubectl
            - name: SQL_PW
              valueFrom:
                secretKeyRef:
                  # Make sure the name of your secret matches the namespace whatever you're deploying 
                  # When the helm chart is deployed through GitHub actions it creates the namespace as <repository_name>-<branch_name>
                  # This way we can have different secrets and thus difference SQL database endpoints for different branches if need be
                  name: {{ .Release.Namespace }}
                  key: SQL_PW
            - name: SQL_HOST_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}
                  key: SQL_HOST_DB
            - name: SQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Namespace }}
                  key: SQL_USER
      imagePullSecrets:
        - name: {{ .Values.dockerConfigJson.secretName }}
